"""
app/agents/orchestrator.py

LangGraph Multi-Agent Orchestrator.
Uses a declarative StateGraph to coordinate the CEO router and specialized agent teams,
streaming real-time Server-Sent Events (SSE) via LangGraph's custom streaming mode.
"""
import logging
import asyncio
from typing import TypedDict

from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
from langgraph.graph import StateGraph, START, END
from langgraph.config import get_stream_writer
from langsmith import traceable

from app.config import DEFAULT_MODEL
from app.agents.context import format_history, build_doc_context, build_image_context, build_user_profile_context
from app.agents.router import resolve_route, RouteDecision
from app.agents.teams.knowledge import astream_knowledge_team
from app.agents.teams.research import astream_research_team
from app.agents.teams.general import astream_general_agent
from app.agents.teams.vision import astream_vision_agent
from app.agents.prompts.orchestrator import FOLLOW_UP_SYSTEM
from app.services.memory import retrieve_memories

logger = logging.getLogger(__name__)

_followup_llm = ChatOpenAI(model=DEFAULT_MODEL, temperature=0.7)


# ---------------------------------------------------------------------------
# History conversion helper
# ---------------------------------------------------------------------------

def _history_to_messages(history: list[dict]) -> list[BaseMessage]:
    """Convert list of {"role": ..., "content": ...} dicts to LangChain BaseMessage objects."""
    result: list[BaseMessage] = []
    for msg in history:
        if msg["role"] == "user":
            result.append(HumanMessage(content=msg["content"]))
        else:
            result.append(AIMessage(content=msg["content"]))
    return result


def _extract_image_summaries_from_history(history: list[dict]) -> str:
    """
    Scan conversation history metadata for image summaries from prior turns.
    Returns a contextual string describing previously uploaded images, or empty string.
    """
    summaries = []
    for msg in history:
        meta = msg.get("metadata", {})
        if meta.get("image_summaries"):
            for summary in meta["image_summaries"]:
                summaries.append(summary)
        elif meta.get("image_count") and msg.get("role") == "user":
            # User uploaded images but no summary saved yet (before this feature existed)
            summaries.append(f"User uploaded {meta['image_count']} image(s) in a previous turn.")

    if not summaries:
        return ""

    return "PREVIOUS IMAGE CONTEXT:\n" + "\n".join(f"- {s}" for s in summaries[-5:])


# ---------------------------------------------------------------------------
# LangGraph Orchestrator State Definition
# ---------------------------------------------------------------------------

class OrchestratorState(TypedDict):
    """
    Typed state dictionary passed across nodes in the LangGraph multi-agent graph.

    Fields:
      messages:        Current conversation history converted into LangChain BaseMessage objects.
      query:           Latest user query text.
      user_id:         Authenticated user UUID for resource isolation.
      conversation_id: Active conversation UUID for per-session document scoping.
      has_documents:   Flag indicating whether documents have been ingested for this conversation.
      images:          Optional list of base64 data URIs for vision analysis.
      image_urls:      Optional list of S3 URLs for persisted images (for future turn reloading).
      user_tz:         Client timezone string (e.g., 'America/New_York') for temporal grounding.
      route:           Primary destination selected by the CEO router.
      final_answer:    Consolidated markdown answer generated by the executed agent team.
      image_history:   Text summary of images from prior turns (injected from metadata).
    """
    messages: list[BaseMessage]
    query: str
    user_id: str
    conversation_id: str
    has_documents: bool
    images: list[str]
    image_urls: list[str]
    user_tz: str | None
    route: str
    final_answer: str
    image_history: str
    doc_names: list[str]


# ---------------------------------------------------------------------------
# LangGraph Nodes
# ---------------------------------------------------------------------------

async def ceo_router_node(state: OrchestratorState) -> dict:
    """
    CEO Router Node:
    Analyzes intent, document presence, images, and history to determine routing.
    Emits an initial 'agent_start' SSE event via LangGraph custom stream writer.
    """
    writer = get_stream_writer()
    if writer is not None:
        writer({"event": "agent_start", "data": {"agent": "ceo", "message": "Thinking..."}})

    has_documents = state.get("has_documents", False)
    images = state.get("images") or []
    has_images = bool(images)

    doc_context = build_doc_context(has_documents)
    image_context = build_image_context(has_images, len(images), has_documents=has_documents)
    history_text = format_history(state["messages"], last_n=20)

    decision: RouteDecision = await resolve_route(
        query=state["query"],
        history_text=history_text,
        doc_context=doc_context,
        has_documents=has_documents,
        has_images=has_images,
        image_context=image_context,
    )

    return {
        "route": decision.primary_route,
    }


def select_route(state: OrchestratorState) -> str:
    """Conditional routing edge function for LangGraph."""
    return state.get("route", "general")


async def general_agent_node(state: OrchestratorState) -> dict:
    """General Web Agent Node: ReAct web search for current events and broad topics."""
    writer = get_stream_writer()
    if writer is not None:
        writer({"event": "agent_start", "data": {"agent": "general", "message": "Thinking..."}})

    tokens = []
    async for token in astream_general_agent(state["query"], state["messages"], user_tz=state.get("user_tz")):
        tokens.append(token)
        if writer is not None:
            writer({"event": "token", "data": {"agent": "general", "content": token}})

    return {"final_answer": "".join(tokens)}


async def vision_agent_node(state: OrchestratorState) -> dict:
    """Multimodal Vision Agent Node: Analyzes uploaded images, optionally with document context."""
    writer = get_stream_writer()
    if writer is not None:
        writer({"event": "agent_start", "data": {"agent": "vision_agent", "message": "Analyzing image..."}})

    # If documents were uploaded previously in this conversation, pre-fetch document summary/context
    doc_context = ""
    if state.get("has_documents"):
        try:
            from app.agents.tools.retriever import build_hybrid_retriever
            retriever_tool = build_hybrid_retriever(
                state["user_id"],
                state["conversation_id"],
                doc_names=state.get("doc_names"),
            )
            search_query = state.get("query", "").strip() or "summarize key points"
            doc_context = await retriever_tool.ainvoke(search_query)
            if not doc_context or "No relevant documents found" in doc_context:
                doc_context = await retriever_tool.ainvoke("summarize document")
        except Exception as exc:
            logger.warning("[Vision] Failed to fetch doc context: %s", exc)

    # Inject prior image summaries into the messages if available
    messages = list(state["messages"])
    image_history = state.get("image_history", "")
    if image_history:
        messages.insert(0, SystemMessage(content=image_history))

    tokens = []
    async for token in astream_vision_agent(
        state["query"],
        state.get("images") or [],
        messages,
        doc_context=doc_context,
    ):
        tokens.append(token)
        if writer is not None:
            writer({"event": "token", "data": {"agent": "vision_agent", "content": token}})

    return {"final_answer": "".join(tokens)}


async def follow_up_node(state: OrchestratorState) -> dict:
    """Direct Conversational Follow-Up Node: Direct answers without tool overhead."""
    writer = get_stream_writer()
    if writer is not None:
        writer({"event": "agent_start", "data": {"agent": "follow_up", "message": "Thinking..."}})

    recent_msgs = state["messages"][-10:] if len(state["messages"]) > 10 else state["messages"]

    # Inject image history so follow-up can reference previously analyzed images
    prefix = []
    image_history = state.get("image_history", "")
    if image_history:
        prefix.append(SystemMessage(content=image_history))

    followup_messages = prefix + [SystemMessage(content=FOLLOW_UP_SYSTEM)] + recent_msgs + [HumanMessage(content=state["query"])]

    tokens = []
    async for chunk in _followup_llm.astream(followup_messages):
        content = chunk.content
        if isinstance(content, str) and content:
            tokens.append(content)
            if writer is not None:
                writer({"event": "token", "data": {"agent": "follow_up", "content": content}})
        elif isinstance(content, list):
            for block in content:
                if isinstance(block, dict) and block.get("type") == "text" and block.get("text"):
                    tokens.append(block["text"])
                    if writer is not None:
                        writer({"event": "token", "data": {"agent": "follow_up", "content": block["text"]}})

    return {"final_answer": "".join(tokens)}


async def knowledge_team_node(state: OrchestratorState) -> dict:
    """Knowledge Team Node: Enterprise Document RAG with CRAG verification."""
    writer = get_stream_writer()
    if writer is not None:
        writer({"event": "agent_start", "data": {"agent": "knowledge_team", "message": "Searching documents..."}})

    tokens = []
    async for evt in astream_knowledge_team(
        state["query"],
        user_id=state["user_id"],
        conversation_id=state["conversation_id"],
        history=state["messages"],
        doc_names=state.get("doc_names"),
    ):
        if evt["type"] == "status":
            if writer is not None:
                writer({"event": "agent_start", "data": {"agent": "knowledge_team", "message": evt["message"]}})
        elif evt["type"] == "token":
            tokens.append(evt["content"])
            if writer is not None:
                writer({"event": "token", "data": {"agent": "knowledge_team", "content": evt["content"]}})

    return {"final_answer": "".join(tokens)}


async def research_team_node(state: OrchestratorState) -> dict:
    """Deep Research Team Node: Multi-step research across ArXiv, PubMed, Wikipedia, Web."""
    writer = get_stream_writer()
    if writer is not None:
        writer({"event": "agent_start", "data": {"agent": "research_team", "message": "Researching..."}})

    tokens = []
    async for evt in astream_research_team(state["query"], history=state["messages"]):
        if evt["type"] == "status":
            if writer is not None:
                writer({"event": "agent_start", "data": {"agent": "research_team", "message": evt["message"]}})
        elif evt["type"] == "token":
            tokens.append(evt["content"])
            if writer is not None:
                writer({"event": "token", "data": {"agent": "research_team", "content": evt["content"]}})

    return {"final_answer": "".join(tokens)}


def _build_orchestrator_graph():
    """
    Compile the top-level LangGraph state graph.
    Adding future agent departments requires only:
      1. Defining a new agent node function
      2. builder.add_node("new_agent", new_agent_node)
      3. Adding the branch in select_route and builder.add_edge("new_agent", END)
    """
    builder = StateGraph(OrchestratorState)

    builder.add_node("ceo_router", ceo_router_node)
    builder.add_node("knowledge_team", knowledge_team_node)
    builder.add_node("research_team", research_team_node)
    builder.add_node("general", general_agent_node)
    builder.add_node("vision_agent", vision_agent_node)
    builder.add_node("follow_up", follow_up_node)

    builder.add_edge(START, "ceo_router")
    builder.add_conditional_edges(
        "ceo_router",
        select_route,
        {
            "knowledge_team": "knowledge_team",
            "research_team": "research_team",
            "general": "general",
            "vision_agent": "vision_agent",
            "follow_up": "follow_up",
        },
    )

    for node_name in ["knowledge_team", "research_team", "general", "vision_agent", "follow_up"]:
        builder.add_edge(node_name, END)

    return builder.compile()


orchestrator_graph = _build_orchestrator_graph()


# ---------------------------------------------------------------------------
# Public streaming entry point (called by chat_stream service)
# ---------------------------------------------------------------------------

@traceable(name="Orchestrator SSE Stream", run_type="chain")
async def astream_graph_events(
    query: str,
    history: list[dict],
    user_id: str,
    conversation_id: str,
    has_documents: bool,
    images: list[str] | None = None,
    image_urls: list[str] | None = None,
    user_tz: str | None = None,
    memory_enabled: bool = True,
    user_profile: dict | None = None,
    doc_names: list[str] | None = None,
):
    """
    Async generator for real-time Server-Sent Events (SSE) streaming powered by LangGraph.

    Execution model:
      1. Converts raw message history dicts into LangChain BaseMessage instances.
      2. Extracts prior image summaries from conversation history metadata.
      3. Retrieves long-term user memories via Mem0 (offloaded via asyncio.to_thread).
      4. Constructs combined user profile & memory context as the leading SystemMessage.
      5. Initializes OrchestratorState and invokes orchestrator_graph.astream() with stream_mode="custom".
      6. Nodes emit SSE events ('agent_start', 'token') in real-time via LangGraph's get_stream_writer().
      7. Yields a final terminal event {"event": "done", "data": {"route": ...}} with execution metadata.
    """
    messages = _history_to_messages(history)
    img_list = images or []

    # Extract image summaries from prior turns in conversation history
    image_history = _extract_image_summaries_from_history(history)

    # Mem0 memory lookup is blocking I/O; run in thread pool to prevent event loop stalls
    memory_context = (await asyncio.to_thread(retrieve_memories, user_id, query)) if memory_enabled else ""
    profile_context = build_user_profile_context(user_profile)

    combined_context = "\n\n".join(filter(None, [profile_context, memory_context, image_history]))
    if combined_context:
        messages.insert(0, SystemMessage(content=combined_context))

    initial_state: OrchestratorState = {
        "messages": messages,
        "query": query,
        "user_id": user_id,
        "conversation_id": conversation_id,
        "has_documents": has_documents,
        "images": img_list,
        "image_urls": image_urls or [],
        "user_tz": user_tz,
        "route": "",
        "final_answer": "",
        "image_history": image_history,
        "doc_names": doc_names or [],
    }

    executed_route = "general"
    # Stream mode "custom" allows subgraphs and node functions to yield domain events via get_stream_writer()
    async for evt in orchestrator_graph.astream(initial_state, stream_mode="custom"):
        if isinstance(evt, dict):
            # Capture the executing specialist department for frontend metadata
            if evt.get("event") == "agent_start" and evt.get("data", {}).get("agent"):
                ag = evt["data"]["agent"]
                if ag not in ("ceo",):
                    executed_route = ag
            yield evt

    # Final event signaling complete transmission of the response stream
    yield {"event": "done", "data": {"route": executed_route}}
